# SonarCloud — Backend Laravel (PHP 8.2)

sonar.projectKey=Fraschesca03_skillhub-backend
sonar.projectName=EC09 - Backend Laravel
sonar.organization=fraschesca03

sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml

sonar.exclusions=vendor/**,node_modules/**,database/**,storage/**,bootstrap/**,public/**,resources/**
sonar.coverage.exclusions=app/Http/Middleware/**,app/Providers/**,app/Mail/**,app/Console/**
