# SonarCloud — Auth Service (Spring Boot / Java)

sonar.projectKey=Fraschesca03_skillhub
sonar.projectName=EC09 - Auth Service
sonar.organization=fraschesca03

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8

sonar.exclusions=target/**
